name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  plugin:
    env:
      PLUGIN_NAME: switch_keyboard_controller
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:3.0.0-dkp-beta
    steps:
    - uses: actions/checkout@v2
    - name: Build release NRO
      run: |
        PATH=$PATH:/root/.cargo/bin /root/.cargo/bin/cargo-skyline skyline build --release
      env:
        HOME: /root
    - name: Upload plugin artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: target/aarch64-skyline-switch/release/libswitch_keyboard_controller.nro
  upload:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - plugin
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: Update Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          allow_override: true
          gzip: false
          tag: beta
          name: beta
          body: >
            This works with hackable Switches running the custom firmware [Atmosphere](https://github.com/Atmosphere-NX/Atmosphere/releases).

            To install, download releases from the following pages:
            - [Atmosphere](https://github.com/Atmosphere-NX/Atmosphere/releases)
            - [Skyline](https://github.com/shadowninja108/Skyline)
            - [NRO Hook Plugin](https://github.com/ultimate-research/nro-hook-plugin)

            You should have the following files in the following locations after downloading and installing to your SD card:
            ```
            SD:/atmosphere/contents/01006A800016E000/exefs/subsdk9
            SD:/atmosphere/contents/01006A800016E000/exefs/main.npdm
            SD:/atmosphere/contents/01006A800016E000/romfs/skyline/plugins/libswitch_keyboard_controller.nro
            SD:/atmosphere/contents/01006A800016E000/romfs/skyline/plugins/libnro_hook.nro
            ```

          files: >
            plugin/libswitch_keyboard_controller.nro
